---
name: sync-ec-tasks

on:
  workflow_dispatch:
  schedule:
    # At 09:00 UTC on Tuesday
    - cron: '0 9 * * 1-5'

permissions:
  contents: read

jobs:
  sync-ec-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout tekton-catalog
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: conforma/tekton-catalog
        ref: main
        path: tekton-catalog

    - name: Checkout ec
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        repository: conforma/cli
        ref: main
        path: cli

    - name: Sync tasks
      run: ./hack/sync-ec-cli-tasks.sh ../cli
      working-directory: tekton-catalog
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
