---
name: sync-ec-tasks

on:
  workflow_dispatch:
  schedule:
    # At 09:00 UTC on Tuesday
    - cron: '0 9 * * 1-5'

permissions:
  contents: read

jobs:
  sync-ec-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout tekton-catalog
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        repository: conforma/tekton-catalog
        ref: main
        path: tekton-catalog

    - name: Checkout ec
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        repository: conforma/cli
        ref: main
        path: cli

    - name: Sync tasks
      run: ./hack/sync-ec-cli-tasks.sh ../cli
      working-directory: tekton-catalog
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
